services:
  app:
    image: ${XITOUMA_IMAGE}
    env_file:
      - .env.production
    ports:
      - "${APP_HOST_PORT:-3001}:3000"
    networks:
      - xitouma-net
    restart: unless-stopped

networks:
  xitouma-net:
    external: true
    name: xitouma-net
