services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3001:3000"
    networks:
      - xitouma-net
    restart: unless-stopped

networks:
  xitouma-net:
    external: true
    name: xitouma-net
